version: '3.4'

services:

  consul:
    image: consul

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identityserver:
    image: ${REGISTRY:-gongap}/identityserver:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/KissU.Applications/KissU.IdentityServer/Dockerfile

  serviceshost:
    image: ${REGISTRY:-gongap}/serviceshost:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/KissU.Microservices/KissU.Services.Hosts/KissU.Services.Host/Dockerfile
    depends_on:
      - consul
      - redis
      - rabbitmq

  serviceshost_a:
    image: ${REGISTRY:-gongap}/serviceshost_a:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/KissU.Microservices/KissU.Services.Hosts/KissU.Services.SampleA.Host/Dockerfile
    depends_on:
      - consul
      - redis
      - rabbitmq
