version: '3.4'

services:

  consul:
    image: consul

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  kissu.services.host:
    image: ${REGISTRY:-gongap}/kissu.services.host:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/KissU.Microservices/KissU.Services.Hosts/KissU.Services.Host/Dockerfile    
    depends_on:
      - consul
      - redis
      - rabbitmq

 kissu.services.stage:
    image: ${REGISTRY:-gongap}/kissu.services.stage:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/KissU.Microservices/KissU.Services.Hosts/KissU.Services.Host/Dockerfile    
    depends_on:
      - consul
      - redis
      - rabbitmq

kissu.services.samplea.host:
    image: ${REGISTRY:-gongap}/kissu.services.samplea.host:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/KissU.Microservices/KissU.Services.Hosts/KissU.Services.Host/Dockerfile    
    depends_on:
      - consul
      - redis
      - rabbitmq

kissu.services.sampleb.host:
    image: ${REGISTRY:-gongap}/kissu.services.sampleb.host:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/KissU.Microservices/KissU.Services.Hosts/KissU.Services.Host/Dockerfile    
    depends_on:
      - consul
      - redis
      - rabbitmq
