// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace KissU.Modules.Theme.DbMigrator.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                "systems");

            migrationBuilder.CreateTable(
                "Language",
                schema: "systems",
                columns: table => new
                {
                    Id = table.Column<Guid>(),
                    Version = table.Column<byte[]>(rowVersion: true, nullable: true),
                    CreatorId = table.Column<Guid>(nullable: true),
                    CreationTime = table.Column<DateTime>(nullable: true),
                    LastModifierId = table.Column<Guid>(nullable: true),
                    LastModificationTime = table.Column<DateTime>(nullable: true),
                    Code = table.Column<string>(maxLength: 10),
                    Text = table.Column<string>(maxLength: 64),
                    Abbr = table.Column<string>(maxLength: 128, nullable: true),
                    IsEnabled = table.Column<bool>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Language", x => x.Id);
                });

            migrationBuilder.CreateTable(
                "LanguageDetail",
                schema: "systems",
                columns: table => new
                {
                    Id = table.Column<Guid>(),
                    MainId = table.Column<Guid>(),
                    CreatorId = table.Column<Guid>(nullable: true),
                    CreationTime = table.Column<DateTime>(nullable: true),
                    LastModifierId = table.Column<Guid>(nullable: true),
                    LastModificationTime = table.Column<DateTime>(nullable: true),
                    Key = table.Column<string>(maxLength: 256),
                    Value = table.Column<string>()
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LanguageDetail", x => x.Id);
                    table.ForeignKey(
                        "FK_LanguageDetail_Language_MainId",
                        x => x.MainId,
                        principalSchema: "systems",
                        principalTable: "Language",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                "IX_LanguageDetail_MainId",
                schema: "systems",
                table: "LanguageDetail",
                column: "MainId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                "LanguageDetail",
                "systems");

            migrationBuilder.DropTable(
                "Language",
                "systems");
        }
    }
}
