nuget install KissU.Abp -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json
nuget install KissU.Abp   -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json                                 
nuget install KissU.WebSocket    -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json                   
nuget install KissU.Grpc       -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json                           
nuget install KissU.Thrift      -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json                         
nuget install KissU.DotNetty          -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json                
nuget install KissU.DotNetty.DNS       -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json           
nuget install KissU.DotNetty.WebSocket   -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json    
nuget install KissU.DotNetty.Http       -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json           
nuget install KissU.DotNetty.Mqtt        -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json         
nuget install KissU.DotNetty.Udp          -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json         
nuget install KissU.Codec.MessagePack    -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json       
nuget install KissU.Codec.ProtoBuffer          -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json  
nuget install KissU.ServiceDiscovery.Consul   -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json 
nuget install KissU.ServiceProxy           -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json          
nuget install KissU.BackgroundServer      -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json       
nuget install KissU.ApiGateWay           -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json           
nuget install KissU.Apm.Skywalking         -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json        
nuget install KissU.Logging.NLog           -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json          
nuget install KissU.Logging.Serilog         -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json        
nuget install KissU.AspNetCore.Kestrel     -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json     
nuget install KissU.AspNetCore.Stage         -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json   
nuget install KissU.AspNetCore.Swagger      -Version 1.7.9 -Source http://package.kissu.com/nuget/nuget/v3/index.json  
