before_script:
  - export PATH=$PATH:./node_modules/.bin/
  # Services Repo List
  - git clone --depth 1 https://username:password@gitlab.com/demo/home.git src/app/routes/home
  - git clone --depth 1 https://username:password@gitlab.com/demo/api.git src/app/routes/api
  - yarn

stages:
  - test
  - build

test job:
  image: trion/ng-cli-karma
  stage: test
  only:
    - master
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm run test-coverage

build job:
  image: node:latest
  stage: build
  only:
    - master
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm run build
